### ISSUE TITLE
High-Quality Hero Image and Engaging Descriptions

### ISSUE THREAD

**Issue by james-adcott-edu** [james-adcott-edu/This-Website-Is-Terrible#3]
# User Story: As a Site User, I want to understand the goal of the website immediately upon arrival so that I can get a visual understanding of its purpose

## Acceptance Criteria:

- [ ] A hero section is present at the top of the homepage.
- [ ] The hero section includes a welcoming headline.
- [ ] There is a prominent Settings dialog open to encourage its immediate use.

## Tasks:

- [ ] Design and implement a hero section with a headline.
- [ ] Ensure the hero section is visually appealing and aligns with the website's theme.
- [ ] Add a toggle-able settings dialog
