### ISSUE TITLE
Include Relevant External Links

### ISSUE THREAD

**Issue by james-adcott-edu** [james-adcott-edu/This-Website-Is-Terrible#4]
# User Story: AS A visitor, I WANT TO access relevant external links SO THAT I CAN find additional resources and information on mental health and wellbeing.

## Acceptance Criteria

- [ ] Nav bar should link to generic resources for mental health and wellbeing
- [ ] Each card should include a relevant link
- [ ] Footer should include social media links

## Tasks

- [ ] Add links to nav bar
- [ ] Add a button on each card with a related external resource
- [ ] Add social media to footer
