### ISSUE TITLE
Identify Bad Mental Health Strategies

### ISSUE THREAD

**Issue by james-adcott-edu** [james-adcott-edu/This-Website-Is-Terrible#7]
# User Story: AS a visitor, I WANT TO identify bad mental health strategies SO THAT I CAN understand the differences and make better choices for my wellbeing.

## Acceptance Criteria

- [ ] The user should be able to see contrasting bad advice for each of the mental health strategies and toggle between them

## Tasks

- [ ] Add contrasting bad advice to the strategy cards
- [ ] Add a toggle-able user settings menu that is fixed to the viewport 
- [ ] Add a content toggle in the user settings
