### ISSUE TITLE
Highlight bad web design

### ISSUE THREAD

**Issue by james-adcott-edu** [james-adcott-edu/This-Website-Is-Terrible#8]
# User Story: AS a visitor, I WANT TO see highlights of good and bad website design for mental wellbeing SO THAT I CAN understand the impact of design choices on user experience and mental health.

## Acceptance Criteria

- [ ] User should be able to toggle between options to make the website progressively easier to read and navigate
- [ ] User should be able to see the impact of images, font choices, colours, intrusive elements

## Tasks

- [x] Add a toggle for images
- [x] Add a toggle for text content
- [x] Add a toggle for colours and contrast
- [x] Add a toggle for fonts and font spacing
- [x] Add a toggle for layout
- [x] Add a toggle for ads
- [ ] Add a toggle for links
